### ISSUE TITLE
Zombies

### ISSUE THREAD

**Issue by ChrystiGalbreath** [BillyGalbreath/Pl3xCraft#33]
Zombies do not pick up items from the ground in a claim as well in unclaimed areas.

**Comment by BillyGalbreath** [comment]
Found out this is due to a GameRule that I set, MobGriefing false. Turns out mobs picking up gear is considered mob griefing.

I can re-enable mob griefing, but this enables creepers to create potholes in unclaimed land and endermen to steal and place blocks around the world.

I will need to add better wilderness protection to the claims plugin before reverting this gamerule.

**Comment by BillyGalbreath** [comment]
https://bitbucket.org/BillyGalbreath/pl3xclaims/commits/4fa6c37764d995ca01089a3801fe08c6104acf74
